# -*- coding: utf-8 -*-
"""test1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I0am6BUeJrU_SWq61kHDIccILAwJj-em
"""

#print()함수 ---주석
print("안녕하세요")
print("정보")

# 주석처리입니다.
# 여긴 실행되지 않아요

'''
이 부분은 주석 처리가 됩니다.
여러 줄을 이렇게 작성할 수 있습니다.
'''
print("실행되는 코드")

#print() 여러 줄 출력
print('''
안녕하세요
정보
1학년 6_8반
프로그래밍
''')

#print() 여러 내용 출력 (,) , + 기호 사용 예시
print("1학년","6_8반","정보")
print("1학년"+"6_8반"+"정보")

#print() , sep 구분 기호
print("1학년","6_8반","정보",sep='??')



#print() , end 기호
print("1학년","6_8반","정보",end='        ')
print("1학년"+"6_8반"+"정보")

#f-문자열 형식